version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - '8080:8080'

  web:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db
      volumes:
        - .:/code

volumes:
  db_data:
